//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBody
    {
        public int ID { get; set; }
        public string BodyDescription { get; set; }
        public string ImageURL { get; set; }
    }
}
